import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/layout/Sidebar'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/theme-provider'
import Form from './_components/Form'
import AddInvoice from './_components/AddInvoice'
import EditInvoice from './_components/EditInvoice'
import DeleteModale from './[id]/_components/DeleteModale'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'InvM',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <ThemeProvider
          defaultTheme="light"
          attribute='class'
        >
          <body className={`${inter.className} `}>
            <main className='flex flex-col md:flex-row min-h-screen bg-gray-100'>
            <DeleteModale />
            <Sidebar />
              <div className='flex-1 flex justify-center relative'> 
                <AddInvoice />
                <EditInvoice />
                {children}
              </div>
            </main>
          </body>
        </ThemeProvider>
      </html>
    </ClerkProvider>
  )
}
